services:
    apikey_authenticator:
          class:  APIBundle\Security\ApiKeyAuthenticator
          public: false
    api_user_provider:
          class: APIBundle\Security\APIUserProvider
          arguments: ["@doctrine_mongodb"]
    kernel.listener.api_exception_listener:
            class: APIBundle\EventListener\APIExceptionListener
            tags:
                - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }