<?php

namespace APIBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * FofCacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FofCacheRepository extends DocumentRepository
{

    /**
     * @param string $apiKey
     * @param int    $depth
     * @return object
     */
    public function getFriendsOfFriends($apiKey, $depth)
    {
        return $this->findOneBy(['apikey' => $apiKey, 'depth' => $depth]);
    }

    /**
     * @param string $id
     * @param int    $progress
     */
    public function updateProgress($id, $progress)
    {
        $this->createQueryBuilder()
            ->update()
            ->field("id")->equals($id)
            ->field("progress")->set($progress)
            ->getQuery()
            ->execute();
    }
}
